//////////
// Do not edit this file

module auto_reset(
    input clock,
    output reset
);
  reg [9:0] shift_reg = 10'b1111111111;
  
  always @(posedge clock)
    shift_reg <= {shift_reg[8:0], 1'b0};
    
  assign reset = shift_reg[9];
endmodule
